apiVersion: v1
kind: Service
metadata:
  name: smart-expense-tracker-service
spec:
  selector:
    app: smart-expense-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
