- name: Deploying Smart Expense Tracker App to Minikube
  hosts: localhost
  tasks:
    - name: Ensures that Minikube is running
      command: minikube status
      register: minikube_status
      changed_when: false

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        src: k8s/deployment.yaml

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        src: k8s/service.yaml
